### ISSUE TITLE
Open Source Backend

### ISSUE THREAD

**Issue by TobiasPressler** [markusstephanides/spengerclub-frontend#20]
For continuation pls. Open Source the Backend or E-Mail to pre18984@spengergasse.at

**Comment by markusstephanides** [comment]
Hi, the backend is already open source: https://github.com/markusstephanides/spengerclub-backend

But it might not work with the current version of the WebUntis Backend, just so you know!

Thanks and have fun!

**Comment by TobiasPressler** [comment]
Do you still own the spenger.club domain?

By the way the backend is still working!
I have the latest Untis API docs an apparently nothing changed.

Thanks!

**Comment by markusstephanides** [comment]
Hi, I don't own the spenger.club domain anymore, it should be available to buy!

Thank you for continuing the project! Are you going to fork the repositories or do you want to be added to the repositories?

**Comment by TobiasPressler** [comment]
Hey

I already forked both repos. Thanks for your help.
