### ISSUE TITLE
Change title appropriately

### ISSUE THREAD

**Issue by elliottuhlenhut** [markusstephanides/spengerclub-frontend#7]
When viewing schedules of classes, teachers or rooms, display them accordingly in the title

**Comment by markusstephanides** [comment]
You mean the title of the website should be changed according to which schedule you have opened? For example if I view the schedule of the class 5BHIF the title should be: "5BHIF - spenger.club"?

**Comment by Lichtfusion** [comment]
Exactly

**Comment by markusstephanides** [comment]
Pushed and online :)

**Comment by DogukanB** [comment]
Feature of the year
